version: "3"
services:
  db:
    image: mysql:5.7
    container_name: avikus
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: avikus
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - mynet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build:
      dockerfile: Dockerfile
    container_name: avikus-api
    links:
      - db
      - db:avikus
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - mynet
networks:
  mynet:
volumes:
  db:
    driver: local
