uvicorn:
  host: 0.0.0.0
  port: 8000
  log_level: info
  reload: false

db_connection:
  mysql_user: root
  mysql_password: avikus
  mysql_server: db
  mysql_database: avikus
  mysql_port: 3306

api_config:
  title: avikus Project
  description: API Server
  version: v1
  docs_url: /docs